#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/bspwm/panel.sh &

################ DESKTOPS #####################

number_of_monitors=$(xrandr | grep -sw 'connected' | cut -d " " -f 1 | wc -l)

if [ $number_of_monitors -eq 3 ]; then
  bspc monitor HDMI1 -d s f
  bspc monitor DP1 -d a d i o
  bspc monitor eDP1 -d u
else
  bspc monitor -d a s d f u i o
fi

################ BASE CONFIG ###################

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme              alternate
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                true  # Set the desktop layout to monocle if there’s only one tiled window in the tree.
bspc config click_to_focus                true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config presel_feedback               true  # Draw the preselection feedback area

bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner

############### COLORS #####################

bspc config normal_border_color		      "#434C5E"
bspc config active_border_color	        "#1e1e1e"
bspc config focused_border_color	      "#81A1C1"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

################ RULES #####################

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

for wm_class in Lxappearance Nitrogen Blueman-manager Qalculate-gtk llpp Viewinor Nm-connection-editor pavucontrol System-config-printer.py; do
  bspc rule -a $wm_class state=floating center=true
done
