#!/usr/bin/env bash

Mod=Mod4
myTerm=alacritty
layoutVertical=0
layoutMax=2

hc() {
  herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-w close
hc keybind $Mod-Return spawn $myTerm
hc keybind $Mod-grave spawn rofi -theme nord -font "Noto 16" -show

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left focus left
hc keybind $Mod-Down focus down
hc keybind $Mod-Up focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Down shift down
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-m split bottom 0.5
hc keybind $Mod-n split right 0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep
hc keybind $Mod-Control-Left resize left +$resizestep
hc keybind $Mod-Control-Down resize down +$resizestep
hc keybind $Mod-Control-Up resize up +$resizestep
hc keybind $Mod-Control-Right resize right +$resizestep

# tags
tag_names=("a" "s" "d" "f" "u" "i" "o")
tag_keys=("a" "s" "d" "f" "u" "i" "o" 0)

# a default tag is renamed to the first from a list
hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}"; do

  # setting default layout to max for all tags except "s"
  if [ "${tag_names[i]}" == "s" ]; then
    hc set default_frame_layout $layoutVertical
  else
    hc set default_frame_layout $layoutMax
  fi

  hc add "${tag_names[$i]}"
  key="${tag_keys[$i]}"

  if ! [ -z "$key" ]; then
    hc keybind "$Mod-$key" use_index "$i"
    hc keybind "$Mod-Shift-$key" move_index "$i"
  fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Shift-s floating toggle
hc keybind $Mod-Shift-x fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space \
  or , and . compare tags.focus.curframe_wcount = 2 \
  . cycle_layout +1 max horizontal vertical \
  , cycle_layout +1 max horizontal vertical grid

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace cycle_monitor
hc keybind Shift-Control-l focus_monitor -r
hc keybind Shift-Control-h focus_monitor -l

hc keybind $Mod-Tab cycle_all +1
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-Shift-i jumpto urgent

#########################################################
####################### THEME ###########################
#########################################################

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# frame theme
hc set frame_border_active_color '#b6c3db'
hc set frame_border_width 3
hc set frame_border_normal_color '#646d7e'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 4

# window theme
hc attr theme.active.color '#d5d5d5'
hc attr theme.normal.color '#1f232c'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 4
hc set frame_padding 1
hc set smart_window_surroundings on
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

#########################################################
####################### RULES ###########################
#########################################################

hc unrule -F
hc rule tag="${tag_names[0]}" class~'([Vv]ivaldi.*|firefox|[Cc]hromium)' # move all browsers to tag 0
hc rule tag="${tag_names[1]}" once class~'([Aa]lacritty|[Kk]itty)'       # move terminal to tag 1 on first call
hc rule tag="${tag_names[2]}" class~'jetbrains-idea|code'
hc rule tag="${tag_names[3]}" class~'Pcmanfm'
hc rule tag="${tag_names[4]}" class~'[Rr]ambox|[Ss]lack'
hc rule tag="${tag_names[5]}" class~'[Ss]potify'
hc rule class~'([Ll]xappearance|[Nn]itrogen|[Bb]lueman-manager|[Qq]alculate-gtk|llpp|Viewinor|[Nn]m-connection-editor|pavucontrol|[Ss]ystem-config-printer(\.py)*)' floating=on floatplacement=center
hc rule class~'[Gg]simplecal' floating=on

hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

#########################################################
################# MONITORS SETUP ########################
#########################################################

hc detect_monitors
# create some virtual monitors (used to test multi-monitor setup on a laptop):
#hc set_monitors 1000x1080+0+0 920x1080+1000+0               # 2-monitor setup
#hc set_monitors 640x1080+0+0 640x1080+640+0 640x1080+1280+0 # 3-monitor setup

hc set swap_monitors_to_get_tag on

#########################################################
######################## PANEL ##########################
#########################################################

~/.config/herbstluftwm/panel.sh

#########################################################
################### AUTOSTART APPS ######################
#########################################################

if hc silent new_attr bool my___is_first_start; then
  alacritty &
  vivaldi-stable &
fi
